insert into client (nom_client, prenom_client, contact) values ('Evaleen', 'Harrowell', '+86 557 326 36');
insert into client (nom_client, prenom_client, contact) values ('Aldwin', 'Cummins', '+55 914 293 14');
insert into client (nom_client, prenom_client, contact) values ('Audry', 'Woodcroft', '+386 992 682 65');
insert into client (nom_client, prenom_client, contact) values ('Colan', 'Livard', '+92 571 740 15');
insert into client (nom_client, prenom_client, contact) values ('Calhoun', 'Gamlyn', '+86 470 154 35');
insert into client (nom_client, prenom_client, contact) values ('Dylan', 'Swain', '+55 537 965 79');
insert into client (nom_client, prenom_client, contact) values ('Patty', 'Gynne', '+63 641 117 28');
insert into client (nom_client, prenom_client, contact) values ('Merrill', 'Tomanek', '+55 651 864 90');
insert into client (nom_client, prenom_client, contact) values ('Brody', 'Sarsons', '+46 863 182 81');
insert into client (nom_client, prenom_client, contact) values ('Weider', 'Volcker', '+55 840 994 86');
insert into client (nom_client, prenom_client, contact) values ('Lanette', 'Castletine', '+55 647 814 14');
insert into client (nom_client, prenom_client, contact) values ('Katlin', 'Rearden', '+1 952 495 021');
insert into client (nom_client, prenom_client, contact) values ('Barbra', 'Eadon', '+62 668 172 14');
insert into client (nom_client, prenom_client, contact) values ('Andromache', 'Blinder', '+51 984 917 43');
insert into client (nom_client, prenom_client, contact) values ('Tyrus', 'Gorick', '+1 979 883 304');
insert into client (nom_client, prenom_client, contact) values ('Nancie', 'Stegell', '+234 811 774 6');
insert into client (nom_client, prenom_client, contact) values ('Tonie', 'Hosburn', '+55 479 950 85');
insert into client (nom_client, prenom_client, contact) values ('Findlay', 'Sutherley', '+33 976 790 45');
insert into client (nom_client, prenom_client, contact) values ('Shelden', 'Coppen', '+63 881 179 73');
insert into client (nom_client, prenom_client, contact) values ('Kirstin', 'Flux', '+33 242 455 19');
insert into client (nom_client, prenom_client, contact) values ('Jania', 'Uccello', '+60 732 374 70');
insert into client (nom_client, prenom_client, contact) values ('Ingram', 'Risdall', '+63 237 442 12');
insert into client (nom_client, prenom_client, contact) values ('Leona', 'Toderi', '+57 582 926 75');
insert into client (nom_client, prenom_client, contact) values ('Robina', 'McIsaac', '+48 960 446 51');
insert into client (nom_client, prenom_client, contact) values ('Guy', 'Cuppleditch', '+420 208 340 2');
insert into client (nom_client, prenom_client, contact) values ('Devland', 'Dallyn', '+56 670 580 37');
insert into client (nom_client, prenom_client, contact) values ('Colene', 'Crackel', '+249 124 258 5');
insert into client (nom_client, prenom_client, contact) values ('Dani', 'Hefferan', '+63 335 752 82');
insert into client (nom_client, prenom_client, contact) values ('Suzi', 'Jaray', '+86 530 737 32');
insert into client (nom_client, prenom_client, contact) values ('Orion', 'Cocher', '+62 557 123 64');
insert into client (nom_client, prenom_client, contact) values ('Winnie', 'Agneau', '+850 270 649 7');
insert into client (nom_client, prenom_client, contact) values ('Massimiliano', 'Aikett', '+55 850 795 12');
insert into client (nom_client, prenom_client, contact) values ('Gerhardt', 'Heardman', '+1 812 460 671');
insert into client (nom_client, prenom_client, contact) values ('Mordy', 'Osipenko', '+351 182 820 2');
insert into client (nom_client, prenom_client, contact) values ('Mag', 'Aseef', '+55 843 822 20');
insert into client (nom_client, prenom_client, contact) values ('Stefanie', 'Du Hamel', '+47 235 295 04');
insert into client (nom_client, prenom_client, contact) values ('Gerhardine', 'Deeley', '+236 891 177 2');
insert into client (nom_client, prenom_client, contact) values ('Anissa', 'Scarlet', '+86 207 796 52');
insert into client (nom_client, prenom_client, contact) values ('Nadine', 'Beamiss', '+57 179 226 58');
insert into client (nom_client, prenom_client, contact) values ('Vergil', 'Dyott', '+353 789 654 1');
insert into client (nom_client, prenom_client, contact) values ('Janna', 'Umbert', '+93 917 917 13');
insert into client (nom_client, prenom_client, contact) values ('Alvin', 'Trim', '+57 440 897 66');
insert into client (nom_client, prenom_client, contact) values ('Melesa', 'Gimenez', '+7 649 438 239');
insert into client (nom_client, prenom_client, contact) values ('Deeyn', 'Whoolehan', '+64 124 897 65');
insert into client (nom_client, prenom_client, contact) values ('Harmon', 'Craister', '+58 131 297 73');
insert into client (nom_client, prenom_client, contact) values ('Kevyn', 'Coners', '+62 349 920 90');
insert into client (nom_client, prenom_client, contact) values ('Niki', 'Elletson', '+86 555 559 74');
insert into client (nom_client, prenom_client, contact) values ('Tom', 'Jakoubek', '+64 542 518 95');
insert into client (nom_client, prenom_client, contact) values ('Alyson', 'Joselson', '+84 423 315 64');
insert into client (nom_client, prenom_client, contact) values ('Ezekiel', 'Blackman', '+60 570 304 83');
insert into client (nom_client, prenom_client, contact) values ('Harmonie', 'Gorusso', '+86 814 193 98');
insert into client (nom_client, prenom_client, contact) values ('Michel', 'Story', '+93 450 145 67');
insert into client (nom_client, prenom_client, contact) values ('Tito', 'Lafond', '+218 766 592 1');
insert into client (nom_client, prenom_client, contact) values ('Ellary', 'Jordeson', '+86 102 239 28');
insert into client (nom_client, prenom_client, contact) values ('Nerta', 'Scrowby', '+86 459 562 11');
insert into client (nom_client, prenom_client, contact) values ('Chrystal', 'Olfert', '+1 704 488 011');
insert into client (nom_client, prenom_client, contact) values ('Lemar', 'Anderbrugge', '+63 180 614 16');
insert into client (nom_client, prenom_client, contact) values ('Alika', 'Gasnoll', '+234 262 980 5');
insert into client (nom_client, prenom_client, contact) values ('Roarke', 'Lickess', '+1 582 345 265');
insert into client (nom_client, prenom_client, contact) values ('Lissie', 'Hargey', '+62 164 187 05');
insert into client (nom_client, prenom_client, contact) values ('Aluino', 'McGrill', '+232 968 858 3');
insert into client (nom_client, prenom_client, contact) values ('Tasha', 'Tutchings', '+33 648 234 57');
insert into client (nom_client, prenom_client, contact) values ('Reamonn', 'Ligertwood', '+55 151 417 15');
insert into client (nom_client, prenom_client, contact) values ('Wolfy', 'Corselles', '+62 391 447 99');
insert into client (nom_client, prenom_client, contact) values ('Horten', 'Challace', '+48 983 642 87');
insert into client (nom_client, prenom_client, contact) values ('Masha', 'Harlowe', '+31 582 872 39');
insert into client (nom_client, prenom_client, contact) values ('Mikaela', 'Alexander', '+86 237 326 78');
insert into client (nom_client, prenom_client, contact) values ('Magnum', 'Williamson', '+86 684 850 43');
insert into client (nom_client, prenom_client, contact) values ('Berenice', 'Hastings', '+7 326 111 850');
insert into client (nom_client, prenom_client, contact) values ('Genia', 'Boothroyd', '+54 153 250 83');
insert into client (nom_client, prenom_client, contact) values ('Etheline', 'Lea', '+46 159 189 95');
insert into client (nom_client, prenom_client, contact) values ('Lief', 'Rowden', '+86 669 201 40');
insert into client (nom_client, prenom_client, contact) values ('Court', 'Starmer', '+354 230 469 0');
insert into client (nom_client, prenom_client, contact) values ('Cloe', 'Brunger', '+63 325 933 83');
insert into client (nom_client, prenom_client, contact) values ('Fifi', 'Gwyneth', '+1 505 766 333');
insert into client (nom_client, prenom_client, contact) values ('Melisse', 'Keays', '+970 348 525 0');
insert into client (nom_client, prenom_client, contact) values ('Aigneis', 'Ivett', '+1 534 200 158');
insert into client (nom_client, prenom_client, contact) values ('Zechariah', 'Heinzel', '+240 726 360 2');
insert into client (nom_client, prenom_client, contact) values ('Angelika', 'Rowaszkiewicz', '+63 216 169 80');
insert into client (nom_client, prenom_client, contact) values ('Brod', 'Heersma', '+7 904 524 615');
insert into client (nom_client, prenom_client, contact) values ('Skippie', 'Ladyman', '+33 527 681 79');
insert into client (nom_client, prenom_client, contact) values ('Edlin', 'Yellowlea', '+1 564 820 421');
insert into client (nom_client, prenom_client, contact) values ('Roderich', 'Boundey', '+976 391 132 7');
insert into client (nom_client, prenom_client, contact) values ('Ardelis', 'Greystoke', '+46 765 400 37');
insert into client (nom_client, prenom_client, contact) values ('Mariam', 'Cardinal', '+1 941 542 814');
insert into client (nom_client, prenom_client, contact) values ('Isis', 'Feige', '+33 807 674 67');
insert into client (nom_client, prenom_client, contact) values ('Zebedee', 'Pullar', '+86 918 303 42');
insert into client (nom_client, prenom_client, contact) values ('Milka', 'Flory', '+1 314 263 486');
insert into client (nom_client, prenom_client, contact) values ('Chrysler', 'Rutledge', '+386 886 650 0');
insert into client (nom_client, prenom_client, contact) values ('Karlyn', 'Sagrott', '+228 203 614 1');
insert into client (nom_client, prenom_client, contact) values ('Dacy', 'Davidesco', '+1 812 406 644');
insert into client (nom_client, prenom_client, contact) values ('Miguel', 'Inkin', '+351 936 829 8');
insert into client (nom_client, prenom_client, contact) values ('Lyle', 'Persence', '+7 957 406 305');
insert into client (nom_client, prenom_client, contact) values ('Forbes', 'Cinderey', '+63 387 978 25');
insert into client (nom_client, prenom_client, contact) values ('Darnall', 'Walstow', '+62 301 544 14');
insert into client (nom_client, prenom_client, contact) values ('Dill', 'Dumblton', '+7 581 960 850');
insert into client (nom_client, prenom_client, contact) values ('Vita', 'Laxe', '+62 472 161 50');
insert into client (nom_client, prenom_client, contact) values ('Florri', 'McElree', '+7 362 884 95');
insert into client (nom_client, prenom_client, contact) values ('Derwin', 'Guterson', '+7 221 113 950');
insert into client (nom_client, prenom_client, contact) values ( 'Josselyn', 'Creenan', '+7 973 142 808');
insert into client (nom_client, prenom_client, contact) values ( 'Matthias', 'Dowall', '+385 351 241 7');
insert into client (nom_client, prenom_client, contact) values ( 'Baird', 'Esley', '+30 777 806 18');
insert into client (nom_client, prenom_client, contact) values ( 'Ailene', 'Mathias', '+86 762 985 43');
insert into client (nom_client, prenom_client, contact) values ( 'Ennis', 'Dummigan', '+48 733 249 33');
insert into client (nom_client, prenom_client, contact) values ( 'Allie', 'Dumelow', '+51 942 517 88');
insert into client (nom_client, prenom_client, contact) values ( 'Seline', 'Ruse', '+86 247 610 70');
insert into client (nom_client, prenom_client, contact) values ( 'Raviv', 'McWard', '+47 100 728 96');
insert into client (nom_client, prenom_client, contact) values ( 'Cornell', 'Lampen', '+880 922 619 7');
insert into client (nom_client, prenom_client, contact) values ( 'Andrei', 'Richardon', '+48 956 532 21');
insert into client (nom_client, prenom_client, contact) values ( 'Gabbi', 'Faint', '+48 794 863 84');
insert into client (nom_client, prenom_client, contact) values ( 'Alexi', 'Lydiate', '+86 177 148 60');
insert into client (nom_client, prenom_client, contact) values ( 'Almeria', 'O''Glassane', '+81 980 959 10');
insert into client (nom_client, prenom_client, contact) values ( 'Chevalier', 'Josskovitz', '+62 629 631 76');
insert into client (nom_client, prenom_client, contact) values ( 'Edyth', 'Ernshaw', '+351 426 242 8');
insert into client (nom_client, prenom_client, contact) values ( 'Bobby', 'Domenge', '+86 398 586 8');
insert into client (nom_client, prenom_client, contact) values ( 'Lenore', 'Hansbury', '+66 666 143 82');
insert into client (nom_client, prenom_client, contact) values ( 'Sergent', 'Blunsom', '+27 600 546 84');
insert into client (nom_client, prenom_client, contact) values ( 'Arlinda', 'Reedy', '+66 270 852 95');
insert into client (nom_client, prenom_client, contact) values ( 'Garek', 'Cornford', '+86 439 767 78');
insert into client (nom_client, prenom_client, contact) values ( 'Karlan', 'Congrave', '+48 415 778 87');
insert into client (nom_client, prenom_client, contact) values ( 'Glynnis', 'Fulstow', '+86 318 967 54');
insert into client (nom_client, prenom_client, contact) values ( 'Agnola', 'Red', '+86 637 892 82');
insert into client (nom_client, prenom_client, contact) values ( 'Garrot', 'McCambrois', '+86 154 682 10');
insert into client (nom_client, prenom_client, contact) values ( 'Mead', 'Wrate', '+359 971 981 2');
insert into client (nom_client, prenom_client, contact) values ( 'Valina', 'O''Luney', '+62 916 984 98');
insert into client (nom_client, prenom_client, contact) values ( 'Abagail', 'Hanratty', '+63 306 152 33');
insert into client (nom_client, prenom_client, contact) values ( 'Hilarius', 'Booij', '+63 262 897 52');
insert into client (nom_client, prenom_client, contact) values ( 'Udale', 'Pont', '+58 938 215 98');
insert into client (nom_client, prenom_client, contact) values ( 'Jacenta', 'Usborn', '+81 241 488 69');
insert into client (nom_client, prenom_client, contact) values ( 'Cherianne', 'Bearham', '+55 816 652 62');
insert into client (nom_client, prenom_client, contact) values ( 'Sarina', 'Trazzi', '+33 703 620 63');
insert into client (nom_client, prenom_client, contact) values ( 'Kalila', 'Gunston', '+33 961 439 06');
insert into client (nom_client, prenom_client, contact) values ( 'Winna', 'Neat', '+7 109 713 50');
insert into client (nom_client, prenom_client, contact) values ( 'Carie', 'Inkin', '+216 388 116 7');
insert into client (nom_client, prenom_client, contact) values ( 'Avrom', 'Shears', '+389 567 306 8');
insert into client (nom_client, prenom_client, contact) values ( 'Caprice', 'MacPake', '+62 485 919 79');
insert into client (nom_client, prenom_client, contact) values ( 'Niall', 'Plaide', '+376 245 910 0');
insert into client (nom_client, prenom_client, contact) values ( 'Kari', 'Willshere', '+995 754 992 4');
insert into client (nom_client, prenom_client, contact) values ( 'Norma', 'Smogur', '+63 496 291 25');
insert into client (nom_client, prenom_client, contact) values ( 'Natalya', 'Vaskov', '+62 603 588 90');
insert into client (nom_client, prenom_client, contact) values ( 'Othelia', 'Braxay', '+92 893 297 29');
insert into client (nom_client, prenom_client, contact) values ( 'Ofelia', 'Stevings', '+45 187 431 99');
insert into client (nom_client, prenom_client, contact) values ( 'Corrianne', 'Gibbins', '+63 665 688 51');
insert into client (nom_client, prenom_client, contact) values ( 'Zenia', 'Fathers', '+93 250 533 79');
insert into client (nom_client, prenom_client, contact) values ( 'Alvina', 'Pietron', '+7 128 345 076');
insert into client (nom_client, prenom_client, contact) values ( 'Di', 'McTague', '+86 875 442 65');
insert into client (nom_client, prenom_client, contact) values ( 'Waly', 'Klesel', '+33 625 143 50');
insert into client (nom_client, prenom_client, contact) values ( 'Carleen', 'Vigurs', '+385 404 809 8');
insert into client (nom_client, prenom_client, contact) values ( 'Christiano', 'Giamo', '+48 424 793 81');
insert into client (nom_client, prenom_client, contact) values ( 'Marji', 'Edis', '+372 637 465 4');
insert into client (nom_client, prenom_client, contact) values ( 'Elspeth', 'Ellaman', '+33 839 385 99');
insert into client (nom_client, prenom_client, contact) values ( 'Darnall', 'Gedling', '+63 747 974 18');
insert into client (nom_client, prenom_client, contact) values ( 'Carrissa', 'Everitt', '+86 815 889 49');
insert into client (nom_client, prenom_client, contact) values ( 'Marcile', 'Rowen', '+60 190 140 25');
insert into client (nom_client, prenom_client, contact) values ( 'Briano', 'Dight', '+48 623 707 79');
insert into client (nom_client, prenom_client, contact) values ( 'Tyler', 'Sizeland', '+86 854 755 25');
insert into client (nom_client, prenom_client, contact) values ( 'Salli', 'Greger', '+62 141 117 06');
insert into client (nom_client, prenom_client, contact) values ( 'Loleta', 'Jehaes', '+86 887 990 59');
insert into client (nom_client, prenom_client, contact) values ( 'Haily', 'Gallyon', '+86 718 938 82');
insert into client (nom_client, prenom_client, contact) values ( 'Weber', 'Bergeon', '+63 259 696 53');
insert into client (nom_client, prenom_client, contact) values ( 'Verne', 'Martinolli', '+977 482 223 1');
insert into client (nom_client, prenom_client, contact) values ( 'Thadeus', 'Piscopo', '+46 930 895 36');
insert into client (nom_client, prenom_client, contact) values ( 'Emile', 'Tweedlie', '+86 482 425 62');
insert into client (nom_client, prenom_client, contact) values ( 'Fredrika', 'Griswaite', '+7 900 635 831');
insert into client (nom_client, prenom_client, contact) values ( 'Millie', 'Dilston', '+7 687 762 056');
insert into client (nom_client, prenom_client, contact) values ( 'Leslie', 'Carragher', '+62 141 698 95');
insert into client (nom_client, prenom_client, contact) values ( 'Lissa', 'Mussett', '+380 171 436 0');
insert into client (nom_client, prenom_client, contact) values ( 'Randie', 'Bartelli', '+62 652 341 76');
insert into client (nom_client, prenom_client, contact) values ( 'Fanechka', 'Baudins', '+351 718 392 8');
insert into client (nom_client, prenom_client, contact) values ( 'Glenine', 'O''Crevan', '+33 882 831 98');
insert into client (nom_client, prenom_client, contact) values ( 'Vivianna', 'Benditt', '+7 684 952 150');
insert into client (nom_client, prenom_client, contact) values ( 'Marya', 'Leipoldt', '+54 849 330 25');
insert into client (nom_client, prenom_client, contact) values ( 'Melisandra', 'Newitt', '+30 542 142 39');
insert into client (nom_client, prenom_client, contact) values ( 'Gert', 'Aleshkov', '+48 666 979 72');
insert into client (nom_client, prenom_client, contact) values ( 'Margaretha', 'Eads', '+380 980 280 7');
insert into client (nom_client, prenom_client, contact) values ( 'Ciel', 'Reeme', '+33 385 897 31');
insert into client (nom_client, prenom_client, contact) values ( 'Eduardo', 'Panther', '+48 569 971 21');
insert into client (nom_client, prenom_client, contact) values ( 'Mabelle', 'Budgen', '+63 355 345 60');
insert into client (nom_client, prenom_client, contact) values ( 'Charmaine', 'Baudry', '+420 799 134 0');
insert into client (nom_client, prenom_client, contact) values ( 'Archibald', 'Aartsen', '+33 723 217 62');
insert into client (nom_client, prenom_client, contact) values ( 'Alida', 'Elvish', '+81 627 315 14');
insert into client (nom_client, prenom_client, contact) values ( 'Rania', 'Eggle', '+86 536 486 69');
insert into client (nom_client, prenom_client, contact) values ( 'Frederick', 'Dallon', '+62 652 930 68');
insert into client (nom_client, prenom_client, contact) values ( 'Milt', 'Kliner', '+86 907 886 49');
insert into client (nom_client, prenom_client, contact) values ( 'Herby', 'Sinkins', '+51 765 527 73');
insert into client (nom_client, prenom_client, contact) values ( 'Emili', 'McKearnen', '+86 322 445 33');
insert into client (nom_client, prenom_client, contact) values ( 'Kristin', 'Towner', '+358 742 135 3');
insert into client (nom_client, prenom_client, contact) values ( 'Edsel', 'Seeviour', '+370 830 448 1');
insert into client (nom_client, prenom_client, contact) values ( 'Lin', 'Nowick', '+86 996 130 49');
insert into client (nom_client, prenom_client, contact) values ( 'Shadow', 'Kybert', '+1 343 154 717');
insert into client (nom_client, prenom_client, contact) values ( 'Natka', 'Drogan', '+850 876 809 50');
insert into client (nom_client, prenom_client, contact) values ( 'Reece', 'Pietz', '+27 933 171 19');
insert into client (nom_client, prenom_client, contact) values ( 'Alick', 'Houlison', '+62 199 176 98');
insert into client (nom_client, prenom_client, contact) values ( 'Mayer', 'Viollet', '+62 814 827 81');
insert into client (nom_client, prenom_client, contact) values ( 'Riordan', 'Hebburn', '+63 163 773 72');
insert into client (nom_client, prenom_client, contact) values ( 'Quinlan', 'Legrice', '+86 964 157 92');
insert into client (nom_client, prenom_client, contact) values ( 'Stanly', 'Gregorio', '+62 681 913 05');
insert into client (nom_client, prenom_client, contact) values ( 'Jojo', 'Ever', '+41 447 452 90');
insert into client (nom_client, prenom_client, contact) values ( 'Steve', 'Lean', '+57 945 610 12');
insert into client (nom_client, prenom_client, contact) values ( 'Antonietta', 'Shearmer', '+48 662 591 04');
insert into client (nom_client, prenom_client, contact) values ( 'Oby', 'Dommett', '+86 946 952 86');
insert into client (nom_client, prenom_client, contact) values ( 'Faith', 'Shewring', '+33 133 831 39');
insert into client (nom_client, prenom_client, contact) values ( 'Adriana', 'Solley', '+49 926 210 20');
insert into client (nom_client, prenom_client, contact) values ( 'Benedetta', 'Colbrun', '+62 657 173 04');
insert into client (nom_client, prenom_client, contact) values ( 'Dorine', 'Burgess', '+86 352 941 59');
insert into client (nom_client, prenom_client, contact) values ( 'Florina', 'Bullock', '+55 517 650 30');
insert into client (nom_client, prenom_client, contact) values ( 'Rhianna', 'Terren', '+230 499 588 4');
insert into client (nom_client, prenom_client, contact) values ( 'Kassia', 'Foxworthy', '+86 498 281 98');
insert into client (nom_client, prenom_client, contact) values ( 'Ariella', 'Bollin', '+359 419 947 6');
insert into client (nom_client, prenom_client, contact) values ( 'Claresta', 'Brushneen', '+33 254 918 74');
insert into client (nom_client, prenom_client, contact) values ( 'Emmalyn', 'Beake', '+7 217 397 96');
insert into client (nom_client, prenom_client, contact) values ( 'Hew', 'Southwell', '+86 487 973 62');
insert into client (nom_client, prenom_client, contact) values ( 'Cory', 'Whickman', '+62 857 183 02');
insert into client (nom_client, prenom_client, contact) values ( 'Estel', 'Blackall', '+62 133 943 6');
insert into client (nom_client, prenom_client, contact) values ( 'Correy', 'Di Iorio', '+86 452 169 00');
insert into client (nom_client, prenom_client, contact) values ( 'Vassili', 'Spellsworth', '+86 690 897 34');
insert into client (nom_client, prenom_client, contact) values ( 'Seana', 'Bogart', '+56 946 112 41');
insert into client (nom_client, prenom_client, contact) values ( 'Gavra', 'Zeal', '+62 206 544 35');
insert into client (nom_client, prenom_client, contact) values ( 'Stefanie', 'Sarsfield', '+351 982 546 6');
insert into client (nom_client, prenom_client, contact) values ( 'Allie', 'Northfield', '+1 397 312 93');
insert into client (nom_client, prenom_client, contact) values ( 'Merna', 'McNutt', '+225 735 307 5');
insert into client (nom_client, prenom_client, contact) values ( 'Lorenza', 'Riolfi', '+48 991 273 41');
insert into client (nom_client, prenom_client, contact) values ( 'Terrence', 'Petofi', '+63 509 571 61');
insert into client (nom_client, prenom_client, contact) values ( 'Sandor', 'Curner', '+33 202 508 65');
insert into client (nom_client, prenom_client, contact) values ( 'Regan', 'Rawnsley', '+220 342 667 0');
insert into client (nom_client, prenom_client, contact) values ( 'Giffie', 'Briton', '+220 562 842 6');
insert into client (nom_client, prenom_client, contact) values ( 'Caresse', 'Gateman', '+98 344 464 82');
insert into client (nom_client, prenom_client, contact) values ( 'Louie', 'Le-Good', '+62 701 473 71');
insert into client (nom_client, prenom_client, contact) values ( 'Travis', 'Averall', '+62 892 546 69');
insert into client (nom_client, prenom_client, contact) values ( 'Vonny', 'Dibble', '+63 869 778 44');
insert into client (nom_client, prenom_client, contact) values ( 'Nobe', 'Empringham', '+62 318 781 42');
insert into client (nom_client, prenom_client, contact) values ( 'Flinn', 'Thal', '+48 967 517 50');
insert into client (nom_client, prenom_client, contact) values ( 'Sherm', 'Redd', '+55 883 138 34');
insert into client (nom_client, prenom_client, contact) values ( 'Kristel', 'Kitley', '+387 661 738 4');
insert into client (nom_client, prenom_client, contact) values ( 'Steffi', 'Tennet', '+66 463 441 62');
insert into client (nom_client, prenom_client, contact) values ( 'Una', 'Torbett', '+45 154 360 73');
insert into client (nom_client, prenom_client, contact) values ( 'Carlynn', 'McCurrie', '+972 900 681 1');
insert into client (nom_client, prenom_client, contact) values ( 'Emyle', 'Blackborn', '+46 617 721 66');
insert into client (nom_client, prenom_client, contact) values ( 'Willa', 'Chishull', '+66 559 471 71');
insert into client (nom_client, prenom_client, contact) values ( 'Valera', 'Malthus', '+1 220 695 334');
insert into client (nom_client, prenom_client, contact) values ( 'Arly', 'McIlrath', '+86 266 553 49');
insert into client (nom_client, prenom_client, contact) values ( 'Bastian', 'Hedger', '+7 457 582 854');
insert into client (nom_client, prenom_client, contact) values ( 'Brendis', 'Marfell', '+92 113 332 08');
insert into client (nom_client, prenom_client, contact) values ( 'Natalina', 'Autrie', '+976 225 150 8');
insert into client (nom_client, prenom_client, contact) values ( 'Kristos', 'Edbrooke', '+86 711 783 32');
insert into client (nom_client, prenom_client, contact) values ( 'Terry', 'Desorts', '+61 260 291 54');
insert into client (nom_client, prenom_client, contact) values ( 'Lucia', 'Reddish', '+48 904 470 96');
insert into client (nom_client, prenom_client, contact) values ( 'Natassia', 'Wickersley', '+86 241 280 58');
insert into client (nom_client, prenom_client, contact) values ( 'Arda', 'Smissen', '+1 571 812 54');
insert into client (nom_client, prenom_client, contact) values ( 'Cesare', 'Loker', '+7 106 655 971');
insert into client (nom_client, prenom_client, contact) values ( 'Paolina', 'Crucetti', '+20 349 461 45');
insert into client (nom_client, prenom_client, contact) values ( 'Porty', 'Rekes', '+598 429 586 0');
insert into client (nom_client, prenom_client, contact) values ( 'Kaylil', 'Dahlbom', '+55 808 968 92');
insert into client (nom_client, prenom_client, contact) values ( 'Stanislas', 'Burridge', '+86 518 361 84');
insert into client (nom_client, prenom_client, contact) values ( 'Talya', 'While', '+63 776 731 40');
insert into client (nom_client, prenom_client, contact) values ( 'Courtnay', 'Shama', '+256 935 711 6');
insert into client (nom_client, prenom_client, contact) values ( 'Walker', 'Gunther', '+81 268 518 77');
insert into client (nom_client, prenom_client, contact) values ( 'Madge', 'Tiffany', '+7 890 280 722');
insert into client (nom_client, prenom_client, contact) values ( 'Laney', 'Lightbody', '+380 189 908 7');
insert into client (nom_client, prenom_client, contact) values ( 'Marilyn', 'Dutnell', '+46 942 590 96');
insert into client (nom_client, prenom_client, contact) values ( 'Rickie', 'Facher', '+850 171 507 9');
insert into client (nom_client, prenom_client, contact) values ( 'Terence', 'Vigours', '+7 904 889 077');
insert into client (nom_client, prenom_client, contact) values ( 'Meryl', 'Ciccarelli', '+7 626 389 359');
insert into client (nom_client, prenom_client, contact) values ( 'Cletis', 'Senton', '+380 948 648 4');
insert into client (nom_client, prenom_client, contact) values ( 'Tamra', 'Solland', '+63 358 654 84');
insert into client (nom_client, prenom_client, contact) values ( 'Felike', 'Meek', '+33 285 932 51');
insert into client (nom_client, prenom_client, contact) values ( 'Sella', 'Court', '+1 347 183 329');
insert into client (nom_client, prenom_client, contact) values ( 'Emlynne', 'Fetherstonhaugh', '+63 981 200 59');
insert into client (nom_client, prenom_client, contact) values ( 'Jayson', 'McBryde', '+86 654 942 23');
insert into client (nom_client, prenom_client, contact) values ( 'Granville', 'Jelfs', '+970 473 585 4');
insert into client (nom_client, prenom_client, contact) values ( 'Karmen', 'Affuso', '+504 469 743 3');
insert into client (nom_client, prenom_client, contact) values ( 'Thebault', 'Hawick', '+7 642 637 929');
insert into client (nom_client, prenom_client, contact) values ( 'Verena', 'Kiebes', '+7 805 228 56');
insert into client (nom_client, prenom_client, contact) values ( 'Carole', 'Iredell', '+86 228 441 39');
insert into client (nom_client, prenom_client, contact) values ( 'Krissy', 'Lassells', '+63 204 115 07');
insert into client (nom_client, prenom_client, contact) values ( 'Nikolaos', 'Bacher', '+62 509 984 90');
insert into client (nom_client, prenom_client, contact) values ( 'Vina', 'MacManus', '+53 246 740 15');
insert into client (nom_client, prenom_client, contact) values ( 'Virginia', 'Bocking', '+242 356 890 7');
insert into client (nom_client, prenom_client, contact) values ( 'Colman', 'Perrinchief', '+86 577 151 06');
insert into client (nom_client, prenom_client, contact) values ( 'Ebeneser', 'Bale', '+86 921 267 77');
insert into client (nom_client, prenom_client, contact) values ( 'Graeme', 'Odd', '+63 998 248 05');
insert into client (nom_client, prenom_client, contact) values ( 'Trudi', 'Albion', '+7 507 561 40');
insert into client (nom_client, prenom_client, contact) values ( 'Shannon', 'Foston', '+54 761 371 46');
insert into client (nom_client, prenom_client, contact) values ( 'Brier', 'Smythin', '+995 496 873 3');
insert into client (nom_client, prenom_client, contact) values ( 'Marika', 'Morgan', '+250 957 186 8');
insert into client (nom_client, prenom_client, contact) values ( 'Maxy', 'Gribbins', '+27 360 803 71');
insert into client (nom_client, prenom_client, contact) values ( 'Vivianna', 'Lawes', '+598 960 235 7');
insert into client (nom_client, prenom_client, contact) values ( 'Saundra', 'Hadaway', '+55 562 624 52');
insert into client (nom_client, prenom_client, contact) values ( 'Lowe', 'Geerdts', '+46 218 281 11');
insert into client (nom_client, prenom_client, contact) values ( 'Zarah', 'Tollett', '+63 698 204 11');
insert into client (nom_client, prenom_client, contact) values ( 'Jayme', 'Chuney', '+62 711 460 71');
insert into client (nom_client, prenom_client, contact) values ( 'Kelcie', 'Savidge', '+7 208 503 49');
insert into client (nom_client, prenom_client, contact) values ( 'Ryley', 'Strodder', '+385 404 774 3');
insert into client (nom_client, prenom_client, contact) values ( 'Donna', 'Thoma', '+62 540 727 19');
insert into client (nom_client, prenom_client, contact) values ( 'Adair', 'Clemenceau', '+254 680 131 0');
insert into client (nom_client, prenom_client, contact) values ( 'Hunfredo', 'Johanning', '+27 776 907 84');
insert into client (nom_client, prenom_client, contact) values ( 'Roshelle', 'Northall', '+1 561 118 089');
insert into client (nom_client, prenom_client, contact) values ( 'Walker', 'Lindback', '+63 108 846 18');
insert into client (nom_client, prenom_client, contact) values ( 'Paton', 'Scotson', '+7 268 587 84');
insert into client (nom_client, prenom_client, contact) values ( 'Vinni', 'Shaul', '+1 814 962 524');
