insert into ville (nom_ville) values ('Toyooka');
insert into ville (nom_ville) values ('Chalu');
insert into ville (nom_ville) values ('Takedamachi');
insert into ville (nom_ville) values ('San Javier');
insert into ville (nom_ville) values ('Paris ');
insert into ville (nom_ville) values ('Ponta Delgada');
insert into ville (nom_ville) values ('Dadianzi');
insert into ville (nom_ville) values ('Yanqul');
insert into ville (nom_ville) values ('Chisong');
insert into ville (nom_ville) values ('Suya');
insert into ville (nom_ville) values ('Nässjö');
insert into ville (nom_ville) values ('Al Minyā');
insert into ville (nom_ville) values ('Mattaldi');
insert into ville (nom_ville) values ('Qalat Bīshah');
insert into ville (nom_ville) values ('Yarmolyntsi');
insert into ville (nom_ville) values ('Pirapozinho');
insert into ville (nom_ville) values ('Ladoeiro');
insert into ville (nom_ville) values ('Bethanie');
insert into ville (nom_ville) values ('Shigongqiao');
insert into ville (nom_ville) values ('Dazu');
insert into ville (nom_ville) values ('Melíti');
insert into ville (nom_ville) values ('Melaka');
insert into ville (nom_ville) values ('Sośnicowice');
insert into ville (nom_ville) values ('Pepayan');
insert into ville (nom_ville) values ('Liushui');
insert into ville (nom_ville) values ('Dajin');
insert into ville (nom_ville) values ('Zbraslav');
insert into ville (nom_ville) values ('Hepu');
insert into ville (nom_ville) values ('Kuaidamao');
insert into ville (nom_ville) values ('Pulosari');
insert into ville (nom_ville) values ('Victoriaville');
insert into ville (nom_ville) values ('Novi Šeher');
insert into ville (nom_ville) values ('Krajan Alastengah');
insert into ville (nom_ville) values ('Cihua');
insert into ville (nom_ville) values ('Meniko');
insert into ville (nom_ville) values ('Sarandi');
insert into ville (nom_ville) values ('Buenavista');
insert into ville (nom_ville) values ('Qorveh');
insert into ville (nom_ville) values ('Talisay');
insert into ville (nom_ville) values ('Bajo');
insert into ville (nom_ville) values ('Curumaní');
insert into ville (nom_ville) values ('Taosha');
insert into ville (nom_ville) values ('Lens');
insert into ville (nom_ville) values ('Jadranovo');
insert into ville (nom_ville) values ('Metu');
insert into ville (nom_ville) values ('Kaabong');
insert into ville (nom_ville) values ('Imatra');
insert into ville (nom_ville) values ('Asahikawa');
insert into ville (nom_ville) values ('Gornje Moštre');
insert into ville (nom_ville) values ('Eiriz');
